[workspace]
members = ["quinn", "quinn-proto", "quinn-udp"]
default-members = ["quinn", "quinn-proto", "quinn-udp"]
resolver = "2"

[workspace.dependencies]
tracing = { version = "0.1.10", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }

[profile.bench]
debug = true

[profile.release]
debug = true
